require('dotenv').config();

exports.configservices = {
PORT:process.env.PORT,
DB_DATABASE:process.env.DB_DATABASE,
DB_PASSWORD:process.env.DB_PASSWORD,
DB_USER:process.env.DB_USER,
DB_HOST:process.env.DB_HOST,
DB_PORT:process.env.DB_PORT,
GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
GOOGLE_CLIENT_SECRET:process.env.GOOGLE_CLIENT_SECRET,
GOOGLE_REDIRECT:process.env.GOOGLE_REDIRECT,
GOOGLE_PASS_REQ_TO_CALLBACK:process.env.GOOGLE_PASS_REQ_TO_CALLBACK,
SESSION_SECRET:process.env.SESSION_SECRET,
SESSION_RESAVE:process.env.SESSION_RESAVE,
SESSION_SAVE_UNINITIALIZED:process.env.SESSION_SAVE_UNINITIALIZED,
}